version: "3.9"

services:
  web:
    build: .
    container_name: django_web
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - "8000"
    networks:
      - backend

  db:
    image: postgres:17-alpine
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/app/staticfiles:ro
    depends_on:
      - web
    networks:
      - backend

volumes:
  postgres_data:
  static_volume:

networks:
  backend:
    driver: bridge