# Generated by Django 5.2 on 2025-05-02 09:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0002_alter_location_latitude_alter_location_longitude"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="Latitude",
            new_name="latitude",
        ),
        migrations.RenameField(
            model_name="location",
            old_name="Longitude",
            new_name="longitude",
        ),
        migrations.RenameField(
            model_name="location",
            old_name="users",
            new_name="user_id",
        ),
    ]
