# Generated by Django 5.2 on 2025-05-02 09:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0004_alter_location_latitude_alter_location_longitude"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="user_id",
            new_name="user",
        ),
    ]
